---
- name: Create download directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true
  loop:
  - "{{ download_dir }}"
  - "{{ extract_dir }}"